env: production

log:
  level: 0
  file: /app/logs/app.log

ffmpeg:
  outputDir: /var/www/media

db:
  url: postgresql://postgres:1@host.docker.internal:5433/stream?sslmode=disable&search_path=public

kafka:
  brokers:
    - kafka:29092

  clientId: go-stream-worker
  version: "3.5.0"

  consumer:
    groupId: stream-worker-group
    initialOffset: oldest
    minBytes: 1024
    maxBytes: 1048576
    maxWaitTime: 2500ms
    sessionTimeout: 10000ms
    rebalanceTimeout: 60000ms

  producer:
    batchSize: 100
    batchTimeoutMs: 100ms
    requiredAcks: -1
    retryMax: 5

minio:
  endpoint: minio:9000
  accessKeyId: minioadmin
  secretAccessKey: minioadminpassword
  bucketName: hls-streams
  useSSL: false
