kafka:
  brokers:
    - kafka:29092
  clientId: go-stream-worker
  version: "3.5.0"

  consumer:
    groupId: stream-worker-group
    sessionTimeoutMs: 30000
    heartbeatIntervalMs: 3000
    maxPollRecords: 10

  producer:
    requiredAcks: all
    retryMax: 5
    compression: snappy
