services:
  nginx-rtmp:
    build: ./nginx
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rtmp.conf:/etc/nginx/rtmp.conf
      - ./hls:/var/www/hls
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # depends_on:
    #   - nest
    #   - stream

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  # nest:
  #   build: ./nest
  #   container_name: nest-api
  #   expose:
  #     - "3001"
  #   command: node dist/main.js
  #   restart: unless-stopped

  # mail-worker:
  #   build: ./nest
  #   container_name: mail-worker
  #   command: node dist/workers/mail/main.js
  #   restart: unless-stopped

  # stream:
  #   build: ./stream
  #   container_name: go-streamer
  #   volumes:
  #     - ./hls:/var/www/hls
  #   restart: unless-stopped
